site_name: Natal

repo_url: https://github.com/hoishing/natal
extra_css:
  - stylesheets/extra.css

theme:
  font:
    text: Varela Round
  name: "material"
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.png
  logo: assets/natal-logo.svg
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to system preference
        
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to dark mode

  features:
    - navigation.instant
    - navigation.tracking
    # - navigation.sections
    - navigation.expand
    # - toc.integrate

plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_signature_annotations: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

nav:
  - Quick Start: index.md
  - References:
      - chart: chart.md
      - classes: classes.md
      - constants: consts.md
      - data: data.md
      - utils: utils.md
      - stats: stats.md
      # - config: config.md
  - License: license.md
  - Author: https://hoishing.github.io
