is_light_theme: false

light_theme:
    fire: "#ff0000"
    earth: "#ffff00"
    air: "#00ff00"
    water: "#0000ff"
    points: "#00ffff"


display:
    mean_node: False
    chiron: True

orb:
    conjunction: 8
    opposition: 7
    trine: 6
    square: 6
    sextile: 5
