[tool.poetry]
name = "natal"
version = "0.1.0"
description = "create Natal Chart in SVG with ease"
authors = ["Kelvin Ng <hoishing@gmail.com>"]
readme = "README.md"
packages = [{ include = "natal", from = "." }]

[tool.poetry.dependencies]
python = "^3.12"
dominate = "^2.9.1"
pyswisseph = "^2.10.3.2"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"
mkdocs-material = "^9.5.31"
pytest = "^8.3.2"
toml = "^0.10.2"
mkdocstrings = { extras = ["python"], version = "^0.25.2" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
